runtime: custom
env: flex

# Note: App Engine Flex environment doesn't support GPUs directly
# For GPU support, use Cloud Run or Compute Engine

# Removing service name to use 'default' service
# service: stt-yt-api

resources:
  cpu: 4
  memory_gb: 16
  disk_size_gb: 30

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.8

env_variables:
  FLASK_ENV: 'production'
  # YOUTUBE_API_KEY should be set in the GCP console environment variables or secret manager